// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// The site is served from a project path on GitHub Pages, so `base` is set.
// Starlight rewrites internal links for it, which is why pages link with
// site-root paths like `/concepts/documents/` and not with the base prefix.
const site = 'https://brown-dash.github.io';
const base = '/Dash-Documentation';

export default defineConfig({
  site,
  base,
  trailingSlash: 'always',
  integrations: [
    starlight({
      title: 'Dash',
      description:
        'Documentation and project history for Dash, a component-based hypermedia system built by Andries van Dam\'s research group at Brown University.',
      logo: {
        src: './public/assets/images/medium-blue-light-blue.png',
        alt: '',
        replacesTitle: false,
      },
      social: [
        { icon: 'github', label: 'GitHub', href: 'https://github.com/brown-dash' },
      ],
      editLink: {
        baseUrl: 'https://github.com/brown-dash/Dash-Documentation/edit/main/',
      },
      lastUpdated: true,
      customCss: ['./src/styles/dash.css'],
      // Starlight ships Pagefind search, breadcrumbs via the sidebar, an
      // on-page table of contents, previous/next links, and mobile navigation.
      // None of that is rebuilt here.
      tableOfContents: { minHeadingLevel: 2, maxHeadingLevel: 3 },
      pagination: true,
      sidebar: [
        {
          label: 'Overview',
          items: [
            { slug: 'index' },
            { slug: 'overview/what-dash-is' },
            { slug: 'overview/current-state' },
          ],
        },
        {
          label: 'Getting started',
          items: [
            { slug: 'getting-started/using-dash' },
            { slug: 'getting-started/environment' },
          ],
        },
        {
          label: 'Concepts',
          items: [
            { slug: 'concepts' },
            { slug: 'concepts/documents' },
            { slug: 'concepts/collections' },
            { slug: 'concepts/links' },
            { slug: 'concepts/trails' },
            { slug: 'concepts/agents' },
            { slug: 'concepts/generative' },
          ],
        },
        {
          label: 'Using Dash',
          collapsed: true,
          // Autogenerated so a new guide page appears without a config edit.
          items: [{ autogenerate: { directory: 'guides', collapsed: true } }],
        },
        {
          label: 'Architecture',
          items: [
            { slug: 'architecture' },
            { slug: 'architecture/extension-points' },
          ],
        },
        {
          label: 'Research and history',
          items: [
            { slug: 'research/projects' },
            { slug: 'research/cohorts' },
            { slug: 'research/cohorts/2026' },
            { slug: 'research/cohorts/2025' },
            { slug: 'research/cohorts/2024' },
            { slug: 'research/cohorts/2023' },
            { slug: 'research/cohorts/2021-2022' },
            { slug: 'research/cohorts/2019-2020' },
            { slug: 'research/people' },
            { slug: 'research/release-history' },
          ],
        },
        {
          label: 'Contributing',
          items: [
            { slug: 'contributing/joining' },
            { slug: 'contributing/documentation' },
          ],
        },
        {
          label: 'Reference',
          items: [
            { slug: 'reference/status-taxonomy' },
            { slug: 'reference/glossary' },
          ],
        },
      ],
    }),
  ],
});
